[project]
org-name = "ballerina"
version = "0.5.0"

[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "xmlutils"
    version = "0.5.0"
    path = "./lib/ballerina-xmlutils-0.5.0-java.jar"
    groupId = "ballerina"
    modules = ["xmlutils"]
