[project]
org-name = "ballerina"
version = "0.0.0"

[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "jvm"
    version = "0.0.0"
    path = "./lib/ballerina-jvm-0.0.0-java.jar"
    groupId = "ballerina"
    modules = ["jvm"]

    [[platform.libraries]]
    artifactId = "asm"
    version = "6.2.1"
    path = "./lib/asm-6.2.1.jar"
    groupId = "org.ow2.asm"
    modules = ["jvm"]
