[project]
org-name = "ballerina"
version = "0.5.0"

[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "jdbc"
    version = "0.5.0"
    path = "./lib/ballerina-java.jdbc-0.5.0-java.jar"
    groupId = "ballerina"
    modules = ["jdbc"]

    [[platform.libraries]]
    artifactId = "jdbc"
    version = "0.5.0"
    path = "./lib/ballerina-sql-0.5.0-java.jar"
    groupId = "ballerina"
    modules = ["jdbc"]