[project]
org-name = "ballerina"
version = "1.0.0"

[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "xslt"
    version = "@project.version@"
    path = "./lib/ballerina-xslt-@project.version@.jar"
    groupId = "ballerina"
    modules = ["xslt"]
