[project]
org-name = "ballerina"
version = "1.0.0"

[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "log-api"
    version = "@project.version@"
    path = "./lib/ballerina-log-api-@project.version@.jar"
    groupId = "ballerina"
    modules = ["log-api"]
