[project]
org-name = "ballerina"
version = "0.0.0"

[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "jvm"
    version = "@project.version@"
    path = "../externals/jvm.jar"
    groupId = "ballerina"
    modules = ["jvm"]

    [[platform.libraries]]
    artifactId = "asm"
    version = "6.2.1"
    path = "../externals/asm.jar"
    groupId = "org.ow2.asm"
    modules = ["jvm"]
