[project]
org-name = "ballerina"
version = "0.9.0"

[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "java.arrays"
    version = "0.9.0"
    path = "./lib/ballerina-java-arrays-0.9.0-java.jar"
    groupId = "ballerina"
    modules = ["java.arrays"]
    
