[project]
org-name = "ballerina"
version = "0.5.0"

[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "mysql"
    version = "0.5.0"
    path = "./lib/ballerina-mysql-0.5.0-java.jar"
    groupId = "ballerina"
    modules = ["mysql"]

    [[platform.libraries]]
    artifactId = "mysql"
    version = "0.5.0"
    path = "./lib/ballerina-sql-0.5.0-java.jar"
    groupId = "ballerina"
    modules = ["mysql"]
