[project]
org-name = "ballerina"
version = "0.7.0"

[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "filepath"
    version = "0.7.0"
    path = "./lib/ballerina-filepath-0.7.0-java.jar"
    groupId = "ballerina"
    modules = ["filepath"]
