[project]
org-name = "ballerina"
version = "0.0.0"

[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "bir"
    version = "0.0.0"
    path = "./lib/ballerina-bir-0.0.0-java.jar"
    groupId = "ballerina"
    modules = ["bir"]
