[project]
org-name = "ballerina"
version = "0.5.0"

[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "jsonutils"
    version = "0.5.0"
    path = "./lib/ballerina-jsonutils-0.5.0-java.jar"
    groupId = "ballerina"
    modules = ["jsonutils"]
