[project]
org-name = "ballerina"
version = "0.0.0"

[platform]
target = "java"

    [[platform.libraries]]
    artifactId = "math"
    version = "@project.version@"
    path = "./lib/ballerina-math-@project.version@.jar"
    groupId = "ballerina"
    modules = ["math"]
