[project]
org-name = "ballerina"
version = "1.0.0"

[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "jwt"
    version = "@project.version@"
    path = "./lib/ballerina-jwt-@project.version@.jar"
    groupId = "ballerina"
    modules = ["jwt"]
