[project]
org-name = "ballerina"
version = "1.0.0"

[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "rabbitmq"
    version = "1.0.0"
    path = "./lib/ballerina-rabbitmq-1.0.0-java.jar"
    groupId = "ballerina"
    modules = ["rabbitmq"]

    [[platform.libraries]]
    artifactId = "amqp-client"
    version = "5.7.3"
    path = "./lib/amqp-client-5.7.3.jar"
    groupId = "com.rabbitmq"
    modules = ["rabbitmq"]
