[project]
org-name = "ballerina"
version = "0.0.0"

[platform]
target = "java"

    [[platform.libraries]]
    artafactId = "mime"
    version = "@project.version@"
    path = "./lib/ballerina-mime-@project.version@.jar"
    groupId = "ballerina"
    modules = ["mime"]

    [[platform.libraries]]
    artafactId = "org.wso2.transport.http.netty"
    version = "6.0.294"
    path = "./lib/org.wso2.transport.http.netty-6.2.4.jar"
    groupId = "org.wso2.transport.http"
    modules = ["mime"]

    [[platform.libraries]]
    artafactId = "mimepull"
    version = "1.9.11"
    path = "./lib/mimepull-1.9.7.jar"
    groupId = "org.jvnet.mimepull"
    modules = ["mime"]

    [[platform.libraries]]
    artafactId = "axiom-api"
    version = "1.2.20"
    path = "./lib/axiom-api-1.2.20.jar"
    groupId = "org.apache.ws.commons.axiom"
    modules = ["mime"]

    [[platform.libraries]]
    artafactId = "commons-logging"
    version = "1.1.1"
    path = "./lib/commons-logging-1.1.1.jar"
    groupId = "commons-logging"
    modules = ["mime"]

    [[platform.libraries]]
    artafactId = "netty-common"
    version = "4.1.34.Final"
    path = "./lib/netty-common-4.1.34.Final.jar"
    groupId = "io.netty"
    modules = ["mime"]

    [[platform.libraries]]
    artafactId = "netty-buffer"
    version = "4.1.34.Final"
    path = "./lib/netty-buffer-4.1.34.Final.jar"
    groupId = "io.netty"
    modules = ["mime"]

    [[platform.libraries]]
    artafactId = "netty-transport"
    version = "4.1.34.Final"
    path = "./lib/netty-transport-4.1.34.Final.jar"
    groupId = "io.netty"
    modules = ["mime"]

    [[platform.libraries]]
    artafactId = "netty-resolver"
    version = "4.1.34.Final"
    path = "./lib/netty-resolver-4.1.34.Final.jar"
    groupId = "io.netty"
    modules = ["mime"]

    [[platform.libraries]]
    artafactId = "netty-handler"
    version = "4.1.34.Final"
    path = "./lib/netty-handler-4.1.34.Final.jar"
    groupId = "io.netty"
    modules = ["mime"]

    [[platform.libraries]]
    artafactId = "netty-codec-http"
    version = "4.1.34.Final"
    path = "./lib/netty-codec-http-4.1.34.Final.jar"
    groupId = "io.netty"
    modules = ["mime"]

    [[platform.libraries]]
    artafactId = "netty-codec"
    version = "4.1.34.Final"
    path = "./lib/netty-codec-4.1.34.Final.jar"
    groupId = "io.netty"
    modules = ["mime"]

    [[platform.libraries]]
    artafactId = "netty-handler-proxy"
    version = "4.1.34.Final"
    path = "./lib/netty-handler-proxy-4.1.34.Final.jar"
    groupId = "io.netty"
    modules = ["mime"]

    [[platform.libraries]]
    artafactId = "netty-codec-http2"
    version = "4.1.34.Final"
    path = "./lib/netty-codec-http2-4.1.34.Final.jar"
    groupId = "io.netty"
    modules = ["mime"]

    [[platform.libraries]]
    artafactId = "commons-pool"
    version = "1.5.6.wso2v1"
    path = "./lib/commons-pool-1.5.6.wso2v1.jar"
    groupId = "commons-pool.wso2"
    modules = ["mime"]

    [[platform.libraries]]
    artafactId = "snakeyaml"
    version = "1.16.0.wso2v1"
    path = "./lib/snakeyaml-1.16.0.wso2v1.jar"
    groupId = "org.wso2.orbit.org.yaml"
    modules = ["mime"]

    [[platform.libraries]]
    artafactId = "bcprov-jdk15on"
    version = "1.61"
    path = "./lib/bcprov-jdk15on-1.61.jar"
    groupId = "org.bouncycastle"
    modules = ["mime"]

    [[platform.libraries]]
    artafactId = "bcpkix-jdk15on"
    version = "1.61"
    path = "./lib/bcpkix-jdk15on-1.61.jar"
    groupId = "org.bouncycastle"
    modules = ["mime"]

    [[platform.libraries]]
    artafactId = "netty-tcnative-boringssl-static"
    version = "2.0.22.Final"
    path = "./lib/netty-tcnative-boringssl-static-2.0.23.Final.jar"
    groupId = "io.netty"
    modules = ["mime"]
